version: "2"

services:

  postgres:
    image: postgres:13
    command: postgres -c 'max_connections=200'
    container_name: postgres
    env_file: postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.2
        

  chainlink_node1:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node1
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink?sslmode=disable
      - PEER_ID=p2p_12D3KooWALTnn7MtMcwhvYbZ4m5W6f7pKDFJGjHnQJyGX1d4RUHe
      - CHAINLINK_PORT=6691
      - CLIENT_NODE_URL=http://localhost:6691
    ports:
      - 6691:6691
    volumes:
      - ./volumes/chainlink1:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_1.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_1.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.3

  chainlink_node2:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node2
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink2?sslmode=disable
      - CHAINLINK_PORT=6692
      - CLIENT_NODE_URL=http://localhost:6692
    ports:
      - 6692:6692
    volumes:
      - ./volumes/chainlink2:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_2.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_2.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.4
    
  chainlink_node3:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node3
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink3?sslmode=disable
      - CHAINLINK_PORT=6693
      - CLIENT_NODE_URL=http://localhost:6693
    ports:
      - 6693:6694
    volumes:
      - ./volumes/chainlink3:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_3.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_3.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.5
        
        
  chainlink_node4:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node4
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink4?sslmode=disable
      - CHAINLINK_PORT=6694
      - CLIENT_NODE_URL=http://localhost:6694
    ports:
      - 6694:6694
    volumes:
      - ./volumes/chainlink4:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_4.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_4.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.7
        
        
  chainlink_node5:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node5
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink5?sslmode=disable
      - CHAINLINK_PORT=6695
      - CLIENT_NODE_URL=http://localhost:6695
    ports:
      - 6695:6695
    volumes:
      - ./volumes/chainlink5:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_5.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_5.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.8
        
        
  chainlink_node6:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node6
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink6?sslmode=disable
      - CHAINLINK_PORT=6696
      - CLIENT_NODE_URL=http://localhost:6696
    ports:
      - 6696:6696
    volumes:
      - ./volumes/chainlink6:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_6.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_6.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.10
        
        
        
  chainlink_node7:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node7
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink7?sslmode=disable
      - CHAINLINK_PORT=6702
      - CLIENT_NODE_URL=http://localhost:6702
    ports:
      - 6702:6702
    volumes:
      - ./volumes/chainlink7:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_7.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_7.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.16
        

  chainlink_node8:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node8
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink8?sslmode=disable
      - CHAINLINK_PORT=6698
      - CLIENT_NODE_URL=http://localhost:6698
    ports:
      - 6698:6698
    volumes:
      - ./volumes/chainlink8:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_8.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_8.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.12
        
        
  chainlink_node9:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node9
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink9?sslmode=disable
      - CHAINLINK_PORT=6699
      - CLIENT_NODE_URL=http://localhost:6699
    ports:
      - 6699:6699
    volumes:
      - ./volumes/chainlink9:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_9.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_9.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.13  
        
        
  chainlink_node10:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node10
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink10?sslmode=disable
      - CHAINLINK_PORT=6700
      - CLIENT_NODE_URL=http://localhost:6700
    ports:
      - 6700:6700
    volumes:
      - ./volumes/chainlink10:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_10.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_10.toml:/home/root/data_job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.14   
        
        
  chainlink_node11:      
    image: ferru97/chainlink-custom3
    container_name: chainlink_node11
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink11?sslmode=disable
      - CHAINLINK_PORT=6701
      - CLIENT_NODE_URL=http://localhost:6701
    ports:
      - 6701:6701
    volumes:
      - ./volumes/chainlink11:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/bootstrap_job.toml:/home/root/job.toml
    links:
      #- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.15       
        


  geth:
    image: ethereum/client-go:v1.10.10
    command: --datadir=/root/.ethereum/devchain --datadir.ancient=/root/.ethereum/devchain --datadir.minfreedisk=0 --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --http.api "db,personal,eth,net,web3,debug,txpool" --http.corsdomain='*' --ws.api "db,personal,eth,net,web3,debug,txpool" --ws.origins='*' --networkid=1337 --http --ws --mine --http.addr="0.0.0.0" --ws.addr="0.0.0.0" --dev --allow-insecure-unlock
    volumes:
      - ./volumes/geth:/root/.ethereum/devchain
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.20


    
  web_server:
    build:
      context: web_server/
      dockerfile: Dockerfile
    image: web_server
    container_name: web_server
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.6
    

      
networks:
  chainlink_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
      
