version: "3.8"
services:
    geth:
      build:
        context: geth/
        dockerfile: Dockerfile
      image: geth
      container_name: geth
      volumes:
        - /mnt/hdd/geth_data:/root/.ethereum
      networks:
        - eth_network
      ports:
        - 8545:8545
        - 8546:8546
        - 8547:8547
        - 30303:30303

volumes:
  eth_data:
     name: eth_data
networks:
  eth_network:
     name: eth_network
