version: "3.8"
services:
    geth:
      build:
        context: geth/
        dockerfile: Dockerfile
      image: geth
      container_name: geth
      volumes:
        - /mnt/hdd/geth_data:/root/.ethereum
      networks:
        - eth_network
      ports:
        - 8545:8545
        - 8546:8546
        - 8547:8547
        - 30303:30303
        
    postgres:
      image: postgres
      container_name: postgres
      env_file: .env
      environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
      ports:
        - 5432:5432
      volumes:
        - /mnt/hdd/db_data:/var/lib/postgresql/data/
      networks:
        - eth_network
        
    chainlink_node:
      image: smartcontract/chainlink:0.10.10
      container_name: chainlink_node
      build:
        contaxt: chainlink-rinkeby/
      env_file: .env
      ports:
        - 6688:6688
      volumes:
        - /mnt/hdd/chainlink_data:/chainlink
      depends_on:
        - postgres
      networks:
        - eth_network

volumes:
  eth_data:
     name: eth_data
networks:
  eth_network:
     name: eth_network
