version: "3.8"
services:
    geth:
      build:
        context: geth/
        dockerfile: geth/Dockerfile
      image: geth
      container_name: geth
      volumes:
        - /mnt/hdd/geth_data:/root/.ethereum
      networks:
        - eth_network
      ports:
        - 8545:8545
        - 8546:8546
        - 8547:8547
        - 30303:30303
        
    postgres:
      image: postgres
      container_name: postgres
      env_file: .env
      environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
      volumes:
        - /mnt/hdd/db_data:/var/lib/postgresql/data/

volumes:
  eth_data:
     name: eth_data
networks:
  eth_network:
     name: eth_network
