
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0xE2a8343B33fa16F295b621417c1DFc7470b2d5E1"
p2pPeerID = "12D3KooWBp8L1Pgs4Rkp5Y2empyh6gp7jEvh9TXyAM6excuKeFn6"
p2pBootstrapPeers = [
"/ip4/10.5.0.8/tcp/3002/p2p/12D3KooWJzw1nwfHLwhSm5EL7G8fhWoom4EBSbR3GEdmqbcN8oos"
]
isBootstrapPeer = false
keyBundleID = "0d3971bec903bad87fcc52b408cd776c7ccc30b90081a7bd5779a889c4585844"
transmitterAddress = "0x4cD73f70fd4f0Cbf61F18132B429742cE3798f9e"
observationTimeout = "10s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    ds1          [type=http method=GET url="http://10.5.0.6:3000/get?tracker=0x9ce23E2B1311F57F060295aCe5d95D0D766d1097"]

    ds1
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
