
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0xE2a8343B33fa16F295b621417c1DFc7470b2d5E1"
p2pPeerID = "12D3KooWMogrWdZ7eB8ynkwLuUaJDESbBsNtHqrVdVSwVxFVnJug"
p2pBootstrapPeers = [
"/ip4/10.5.0.8/tcp/3002/p2p/12D3KooWJzw1nwfHLwhSm5EL7G8fhWoom4EBSbR3GEdmqbcN8oos"
]
isBootstrapPeer = false
keyBundleID = "af74850033e97d138095836a8a526fc1e47d8749e27d929cf06e1c30ee59e290"
transmitterAddress = "0xaCeadFb4b07c035e865Cc342B45f983C2D12B6f5"
observationTimeout = "10s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    ds1          [type=http method=GET url="http://10.5.0.6:3000/get?tracker=0x9ce23E2B1311F57F060295aCe5d95D0D766d1097"]

    ds1
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
