
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x900eC4a33a3D5De03Ac710cF5F62bE34edD36ca1"
p2pPeerID = "12D3KooWLcK6UTuXDSAdTtFwBk89wrSQx9rCy1SqiiHzkQoXfv7m"
p2pBootstrapPeers = [
"/ip4/10.5.0.8/tcp/3002/p2p/12D3KooWDG8UpotmWtAqnSZ337kU92ijf4CL1v94XFau1QawyFr1"
]
isBootstrapPeer = false
keyBundleID = "b10ffb527b4486689d07bc40923a3ede6d3bedce8fc968a2b626cad3256ce2b3"
transmitterAddress = "0x7E836AF68696ACe5509dC3B218081befcD6114B4"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0xFf77d84b22eC78836DE318a57f5B33282d8978CF&oid=0x7E836AF68696ACe5509dC3B218081befcD6114B4&depositlimitation=0x850Ed1F684BD88d1A0136be1b75A97870ACF43cB"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
