
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x900eC4a33a3D5De03Ac710cF5F62bE34edD36ca1"
p2pPeerID = "12D3KooWRef2vU6aoHaGZrTpqaBGoPDvzRkej77CafnbJ8Baggcy"
p2pBootstrapPeers = [
"/ip4/10.5.0.8/tcp/3002/p2p/12D3KooWDG8UpotmWtAqnSZ337kU92ijf4CL1v94XFau1QawyFr1"
]
isBootstrapPeer = false
keyBundleID = "006ef5af0cf7517e973a686c138ff3a04f733a84b3565982a3efe7b8771caa7e"
transmitterAddress = "0x0041eB4b6818CECB501c5520f20e93163CC7F2b7"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0xFf77d84b22eC78836DE318a57f5B33282d8978CF&oid=0x0041eB4b6818CECB501c5520f20e93163CC7F2b7&depositlimitation=0x850Ed1F684BD88d1A0136be1b75A97870ACF43cB"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
