version: "2"

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file: postgres.env
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    restart: unless-stopped
        
  geth:
    build:
      context: geth/
      dockerfile: Dockerfile
    image: geth
    container_name: geth
    volumes:
      - geth-data:/root/.ethereum
    expose:
      - "8545"
      - "8546"
      - "8547"
      - "30303"
    restart: unless-stopped

  chainlink_node:      
    image: smartcontract/chainlink:latest
    container_name: chainlink_node
    command: ["local", "n", "-p", "/chainlink/.password", "-a", "/chainlink/.api"]
    env_file:
      - ./chainlink.env
    ports:
      - 6688:6688
    volumes:
      - chainlink-data:/chainlink
    links:
      - "geth"
      - "postgres"
    restart: unless-stopped
    
    
volumes:
  geth-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/hdd/docker_volumes/geth-data'
      
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/hdd/docker_volumes/db-data'
  
  chainlink-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/hdd/docker_volumes/chainlink'
      
